### ISSUE TITLE
在没有java的情况下无法启动php？

### ISSUE THREAD

**Issue by Gerhut** [fex-team/fis-command-server#9]
可否使用`php -S`的方式启动？

**Comment by xiangshouding** [comment]
嗯，可以，其实 fis-command-server 就是一个简单的web服务而已；

那么如果你想用 php -S 代替是可以的；

```
fis release -d ../output
cd ../output
php -S 127.0.0.1
```

假设你用的是 fis-plus 需要这么干

```
fisp release -d ../output
cd ../output
fisp server install server-env --root ./
php -S 127.0.0.1:8080 ./index.php
```

最后其实就再也不需要执行 fis(p) server start  了，因为你用 php 内建 server 代替了它。

**Comment by Gerhut** [comment]
啊抱歉。。其实我是想发一个 enhancement

我的意思是

    fis server start --type php

在没有 Java（或者 Java 有问题）的情况下（好像）是不能启动 php 服务器的

在代码内搞成直接`exec 'php -S'` 的方式启动服务器是不是就可以忽略 java 的依赖，泛用性更好一些。

**Comment by xiangshouding** [comment]
后续打算 Server 去除对 php，java 的支持，因为发现没啥必要，大家都能很轻松的用上一个 Server

**Comment by Gerhut** [comment]
了解了。。。我自己去写插件吧
